// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"time"
)

type AirlineCompany struct {
	CompanyID   int64
	CompanyName string
	IataCode    string
	MainAirport string
	CreatedAt   time.Time
}
