INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'AT4','AT43', 'Aerospatiale/Alenia ATR 42-300 / 320', 716,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'AT5','AT45', 'Aerospatiale/Alenia ATR 42-500', 127,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'ATR','   N ', 'Aerospatiale/Alenia ATR 42/ ATR 72', 275,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'AT7','AT72', 'Aerospatiale/Alenia ATR 72', 536,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'SSC','CONC', 'Aerospatiale/BAC Concorde', 348,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'AB3','A30B', 'Airbus A300 pax', 401,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'AB6','A306', 'Airbus A300-600 pax', 118,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '31F','A310', 'Airbus A310 Freighter', 601,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '310','A310', 'Airbus A310 all pax models', 703,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '31X','A310', 'Airbus A310-200 Freighter', 459,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '312','A310', 'Airbus A310-200 pax', 151,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '31Y','A310', 'Airbus A310-300 Freighter', 540,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '313','A310', 'Airbus A310-300 pax', 531,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '32S','   N ', 'Airbus A318/319/320/321', 627,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '318','A318', 'Airbus A318', 380,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '319','A319', 'Airbus A319', 298,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '320','A320', 'Airbus A320-100/200', 309,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '321','A321', 'Airbus A321-100/200', 456,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '330','A330', 'Airbus A330 all models', 779,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '332','A332', 'Airbus A330-200', 205,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '333','A333', 'Airbus A330-300', 646,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '340','A340', 'Airbus A340 all models', 770,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '342','A342', 'Airbus A340-200', 207,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '343','A343', 'Airbus A340-300', 166,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '345','A345', 'Airbus A340-500', 208,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '346','A346', 'Airbus A340-600', 391,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '38F','   N ', 'Airbus A380 Freighter', 794,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '380','   N ', 'Airbus A380 pax', 126,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '388','   N ', 'Airbus A380-800 pax', 379,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'A4F','A124', 'Antonov AN-124 Ruslan', 229,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'ANF','AN12', 'Antonov AN-12', 196,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'A40','A140', 'Antonov AN-140', 185,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'A30','AN30', 'Antonov AN-30', 165,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'A32','AN32', 'Antonov AN-32', 551,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'AR1','RJ1H', 'Avro RJ100 Avroliner', 352,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'AR7','RJ70', 'Avro RJ70 Avroliner', 495,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'ARJ','   N ', 'Avro RJ70 RJ85 / RJ100 Avroliner', 690,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'AR8','RJ85', 'Avro RJ85 Avroliner', 737,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'AX1','RX1H', 'Avro RJX100', 118,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'ARX','   N ', 'Avro RJX85 RJX100', 451,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '14F','   N ', 'BAe 146 Freighter (-100/200/300QT)', 793,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '14X','B461', 'BAe 146 Freighter (-100QT & QC)', 151,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '14Y','B462', 'BAe 146 Freighter (-200QT & QC)', 552,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '14Z','B463', 'BAe 146 Freighter (-200QT & QC)', 541,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '146','   N ', 'BAe 146 all pax models', 123,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '141','B461', 'BAe 146-100 Pax', 319,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '142','B462', 'BAe 146-200 Pax', 191,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '143','B463', 'BAe 146-300 Pax', 747,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '70M','B703', 'Boeing 707 Combi', 776,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '70F','B703', 'Boeing 707 Freighter', 479,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '703','B703', 'Boeing 707-300 pax', 754,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '707','   N ', 'Boeing 707/720 all pax models', 433,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '717','B712', 'Boeing 717', 577,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '72M','   N ', 'Boeing 727 Combi', 706,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '72F','   N ', 'Boeing 727 Freighter (-100/200)', 103,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '727','   N ', 'Boeing 727 all pax models', 150,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '72X','B721', 'Boeing 727-100 Freighter', 213,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '72B','B721', 'Boeing 727-100 Mixed Configuration', 462,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '721','B721', 'Boeing 727-100 pax', 647,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '72S','B722', 'Boeing 727-200 Advanced pax', 365,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '72Y','B722', 'Boeing 727-200 Freighter', 738,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '72C','B722', 'Boeing 727-200 Mixed Configuration', 377,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '722','B722', 'Boeing 727-200 pax', 389,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '73F','   N ', 'Boeing 737 all Freighter models', 437,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '737','   N ', 'Boeing 737 all pax models', 206,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '731','B731', 'Boeing 737-100 pax', 134,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '73M','B732', 'Boeing 737-200 Combi', 338,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '73X','B732', 'Boeing 737-200 Freighter', 494,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '732','B732', 'Boeing 737-200 pax', 455,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '73Y','B733', 'Boeing 737-300 Freighter', 284,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '733','B733', 'Boeing 737-300 pax', 167,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '734','B734', 'Boeing 737-400 pax', 550,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '735','B735', 'Boeing 737-500 pax', 618,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '736','B736', 'Boeing 737-600 pax', 639,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '73W','B737', 'Boeing 737-700 (winglets) pax', 228,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '73G','B737', 'Boeing 737-700 pax', 209,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '73H','B738', 'Boeing 737-800 (winglets) pax', 425,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '738','B738', 'Boeing 737-800 pax', 316,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '739','B739', 'Boeing 737-900 pax', 218,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '74M','   N ', 'Boeing 747 all Combi models', 386,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '74F','   N ', 'Boeing 747 all Freighter models', 275,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '747','   N ', 'Boeing 747 all pax models', 547,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '74T','B741', 'Boeing 747-100 Freighter', 574,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '741','B741', 'Boeing 747-100 pax', 181,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '74C','B742', 'Boeing 747-200 Combi', 485,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '74X','B742', 'Boeing 747-200 Freighter', 407,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '742','B742', 'Boeing 747-200 pax', 181,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '74U','B743', 'Boeing 747-300 / 747-200 SUD Freighter', 615,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '74D','B743', 'Boeing 747-300 Combi', 107,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '743','B743', 'Boeing 747-300 pax', 556,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '74J','B744', 'Boeing 747-400 (Domestic) pax', 230,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '74E','B744', 'Boeing 747-400 Combi', 729,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '74Y','B744', 'Boeing 747-400 Freighter', 152,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '744','B744', 'Boeing 747-400 pax', 689,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '74L','N74S', 'Boeing 747SP', 430,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '74V','B74R', 'Boeing 747SR Freighter', 440,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '74R','B74R', 'Boeing 747SR pax', 444,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '75M','B752', 'Boeing 757 Mixed Configuration', 376,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '757','   N ', 'Boeing 757 all pax models', 708,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '752','B752', 'Boeing 757-200 pax', 207,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '753','B753', 'Boeing 757-300 pax', 435,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '76F','   N ', 'Boeing 767 all Freighter models', 135,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '767','   N ', 'Boeing 767 all pax models', 301,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '76X','B762', 'Boeing 767-200 Freighter', 485,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '762','B762', 'Boeing 767-200 pax', 319,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '76Y','B763', 'Boeing 767-300 Freighter', 756,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '763','B763', 'Boeing 767-300 pax', 432,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '764','B764', 'Boeing 767-400 pax', 728,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '777','   N ', 'Boeing 777 all pax models', 203,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '773','B773', 'Boeing 777-300 pax', 667,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'ATP','ATP', 'British Aerospace ATP', 528,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'JST','   N ', 'British Aerospace Jetstream 31 32 41', 505,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'J31','JS31', 'British Aerospace Jetstream 31', 579,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'J41','JS41', 'British Aerospace Jetstream 41', 203,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'B12','BA11', 'British Aerospace One Eleven 200', 578,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'B13','BA11', 'British Aerospace One Eleven 300', 289,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'B14','BA11', 'British Aerospace One Eleven 400/475', 790,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'B15','BA11', 'British Aerospace One Eleven 500', 628,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'B11','BA11', 'British Aerospace One Eleven', 295,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'BNT','TRIS', 'Britten-Norman BN-2A Mk III Trislander', 701,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'CS2','C212', 'CASA / IPTN 212 Aviocar', 274,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'CS5','CN35', 'CASA / IPTN CN-235', 455,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'CL4','CL44', 'Canadair CL-44', 112,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'CCJ','CL60', 'Canadair Challenger', 504,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'CR1','CRJ1', 'Canadair Regional Jet 100', 487,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'CR2','CRJ2', 'Canadair Regional Jet 200', 247,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'CR7','CRJ7', 'Canadair Regional Jet 700', 548,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'CR9','CRJ9', 'Canadair Regional Jet 900', 318,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'CRJ','   N ', 'Canadair Regional Jet', 325,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'DF2','   N ', 'Dassault Falcon 10 100 20 200 2000', 743,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'DF3','   N ', 'Dassault Falcon 50 900', 365,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'DFL','   N ', 'Dassault Falcon', 578,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'DHD','DOVE', 'De Havilland DH.104 Dove', 734,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'DHH','HERN', 'De Havilland DH.114 Heron', 465,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'DHO','DHC3', 'De Havilland DHC-3 Otter Turbo Otter', 241,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'DHL','DHC3', 'De Havilland DHC-3 Turbo Otter', 422,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'DH7','DHC7', 'De Havilland DHC-7 Dash 7', 419,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'DH8','   N ', 'De Havilland DHC-8 Dash 8 all models', 484,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'DH1','DH8A', 'De Havilland DHC-8-100 Dash 8 8Q', 469,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'DH2','DH8B', 'De Havilland DHC-8-200 Dash 8 8Q', 613,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'DH3','DH8C', 'De Havilland DHC-8-300 Dash 8 8Q', 287,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'DH4','DH8D', 'De Havilland DHC-8-400 Dash 8Q', 180,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'D1F','DC10', 'Douglas DC-10 all Freighters', 465,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'D10','DC10', 'Douglas DC-10 pax', 378,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'D1X','DC10', 'Douglas DC-10-10 Freighter', 716,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'D11','DC10', 'Douglas DC-10-10/15 pax', 381,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'D1Y','DC10', 'Douglas DC-10-30 / 40 Freighters', 542,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'D1C','DC10', 'Douglas DC-10-30/40 pax', 328,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'DC9','DC9', 'Douglas DC-9 all pax models', 339,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'D91','DC91', 'Douglas DC-9-10 pax', 748,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'D92','DC92', 'Douglas DC-9-20 pax', 365,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'D93','DC93', 'Douglas DC-9-30 pax', 696,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'D94','DC94', 'Douglas DC-9-40 pax', 228,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'D95','DC95', 'Douglas DC-9-50 pax', 502,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'EMJ','   N ', 'Embraer 170/190', 740,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'E70','E170', 'Embraer 170', 249,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'E75','E175', 'Embraer 175', 213,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'E90','E190', 'Embraer 190', 103,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'E95','E195', 'Embraer 195', 108,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'EMB','E110', 'Embraer EMB.110 Bandeirnate', 589,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'EM2','E120', 'Embraer EMB.120 Brasilia', 591,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'ERJ','   N ', 'Embraer RJ135 / RJ140 / RJ145', 311,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'ER3','E135', 'Embraer RJ135', 112,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'ERD','   N ', 'Embraer RJ140', 310,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'ER4','E145', 'Embraer RJ145 Amazon', 432,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'MBH','B105', 'Eurocopter (MBB) Bo.105', 435,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'APH','   N ', 'Eurocopter SA330 Puma/AS332 Super Puma', 199,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'NDH','S65C', 'Eurocopter SA365C SA365N Dauphin 2', 471,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'SWM','   N ', 'Fairchild (Swearingen) SA26 SA226 SA227 Metro Merlin Expediter', 115,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'FRJ','J328', 'Fairchild Dornier 328JET', 529,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'D28','D228', 'Fairchild Dornier Do.228', 777,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'D38','D328', 'Fairchild Dornier Do.328', 121,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'F50','F50', 'Fokker 50', 591,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'F70','F70', 'Fokker 70', 503,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'F21','F28', 'Fokker F.28 Fellowship 1000', 771,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '100','F100', 'Fokker F100', 490,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'GRG','G21', 'Grumman G.21 Goose', 285,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'GRJ','   N ', 'Gulfstream G-1159 II III IV V', 434,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'ACP','AC68', 'Gulfstream/Rockwell Commander', 783,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'ACT','AC90', 'Gulfstream/Rockwell Turbo Commander', 527,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'ACD','   N ', 'Gulfstream/Rockwell Turbo Commander', 747,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'H25','   N ', 'Hawker Siddeley HS.125', 554,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'HS7','A748', 'Hawker Siddeley HS.748', 346,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'I14','I114', 'Ilyushin IL114', 628,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'I9M','IL96', 'Ilyushin IL96M pax', 147,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'L4T','L410', 'LET 410', 247,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'L11','L101', 'Lockheed L-1011 50 100 150 200 250', 185,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'L15','L101', 'Lockheed L-1011 500 Tristar pax', 189,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'L1F','L101', 'Lockheed L-1011 Tristar Freighter', 250,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'L10','L101', 'Lockheed L-1011 Tristar pax', 272,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'LOH','C130', 'Lockheed L-182 282 382 L-100 Hercules', 242,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'MIH','MI8', 'MIL Mi-8 / Mi-17 / Mi-171 / Mil-172', 507,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'M1F','MD11', 'McDonnell Douglas MD11 Freighter', 445,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'M1M','MD11', 'McDonnell Douglas MD11 Mixed Conf.', 178,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'M11','MD11', 'McDonnell Douglas MD11 pax', 133,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'M80','MD80', 'McDonnell Douglas MD80', 735,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'M81','MD81', 'McDonnell Douglas MD81', 465,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'M82','MD82', 'McDonnell Douglas MD82', 739,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'M83','MD83', 'McDonnell Douglas MD83', 169,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'M87','MD87', 'McDonnell Douglas MD87', 544,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'M88','MD88', 'McDonnell Douglas MD88', 640,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'M90','MD90', 'McDonnell Douglas MD90', 695,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'MU2','MU2', 'Mitsubishi Mu-2', 796,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'YS1','YS11', 'NAMC YS-11', 488,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'BES','B190', 'Raytheon Beechcraft 1900/1900C', 217,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'BEH','B190', 'Raytheon Beechcraft 1900D', 345,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'S20','SB20', 'Saab 2000', 193,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'SF3','SF34', 'Saab SF340A/B', 324,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'SHB','BELF', 'Shorts SC-5 Belfast', 582,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'SHS','SC7', 'Shorts SC-7 Skyvan', 553,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'SH3','SH33', 'Shorts SD.330', 475,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'SH6','SH36', 'Shorts SD.360', 423,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'S58','S58T', 'Sikorsky S-58T', 407,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'S61','S61', 'Sikorsky S-61', 268,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'S76','S76', 'Sikorsky S-76', 707,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'T20','T204', 'Tupolev Tu-204 / Tu-214', 396,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'TU3','T134', 'Tupolev Tu134', 212,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'TU5','T154', 'Tupolev Tu154', 311,1);
