// This file is generated by GoAdmin CLI adm.
package main

import "github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"

// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// "airline_company" => http://localhost:9033/admin/info/airline_company
// "aircrafts_data" => http://localhost:9033/admin/info/aircrafts_data
// "airports_data" => http://localhost:9033/admin/info/airports_data
//
// example end
var Generators = map[string]table.Generator{

	"airline_company": GetAirlineCompanyTable,
	"aircrafts_data":  GetAircraftsDataTable,
	"airports_data":   GetAirportsDataTable,

	// generators end
}
