CREATE TABLE Schedule (
    id INT AUTO_INCREMENT PRIMARY KEY,
    airline_code VARCHAR(10) NOT NULL,
    flight_number INT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    days_of_week VARCHAR(50) NOT NULL,
    origin_code CHAR(3) NOT NULL,
    destination_code CHAR(3) NOT NULL,
    boarding_time TIME NOT NULL,
    landing_time TIME NOT NULL,
    elapsed_time TIME NOT NULL,
    cabin CHAR(1) NOT NULL,
    cabin_capacity INT NOT NULL,
    segment_specificity_id INT,
    cabin_code VARCHAR(10),
    class_code_list VARCHAR(255),
    fare_family_id INT,
    fratt5_curve_id INT,
    fare_family_disutility_curve_id INT,
    PRIMARY KEY (id)
);
