// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: airport.sql

package db

import (
	"context"
)

const createAirport = `-- name: CreateAirport :one
INSERT INTO airports(
iata_code, 
icao_code, 
name, 
city,
timezone
) VALUES
(  $1 , $2 , $3 , $4, $5
)
RETURNING id, iata_code, icao_code, name, city, timezone
`

type CreateAirportParams struct {
	IataCode string `json:"iata_code"`
	IcaoCode string `json:"icao_code"`
	Name     string `json:"name"`
	City     string `json:"city"`
	Timezone string `json:"timezone"`
}

//subdivision_code
//coordinates
func (q *Queries) CreateAirport(ctx context.Context, arg CreateAirportParams) (Airport, error) {
	row := q.db.QueryRow(ctx, createAirport,
		arg.IataCode,
		arg.IcaoCode,
		arg.Name,
		arg.City,
		arg.Timezone,
	)
	var i Airport
	err := row.Scan(
		&i.ID,
		&i.IataCode,
		&i.IcaoCode,
		&i.Name,
		&i.City,
		&i.Timezone,
	)
	return i, err
}

const deleteAirports = `-- name: DeleteAirports :exec
DELETE FROM airports
WHERE id = $1
RETURNING id, iata_code, icao_code, name, city, timezone
`

func (q *Queries) DeleteAirports(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAirports, id)
	return err
}

const getAirport = `-- name: GetAirport :one
SELECT id, iata_code, icao_code, name, city, timezone FROM airports
WHERE iata_code = $1 LIMIT 1
`

func (q *Queries) GetAirport(ctx context.Context, iataCode string) (Airport, error) {
	row := q.db.QueryRow(ctx, getAirport, iataCode)
	var i Airport
	err := row.Scan(
		&i.ID,
		&i.IataCode,
		&i.IcaoCode,
		&i.Name,
		&i.City,
		&i.Timezone,
	)
	return i, err
}

const listAirport = `-- name: ListAirport :many
SELECT id, iata_code,
name ,
city
FROM airports
ORDER BY id
`

type ListAirportRow struct {
	ID       int64  `json:"id"`
	IataCode string `json:"iata_code"`
	Name     string `json:"name"`
	City     string `json:"city"`
}

func (q *Queries) ListAirport(ctx context.Context) ([]ListAirportRow, error) {
	rows, err := q.db.Query(ctx, listAirport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAirportRow{}
	for rows.Next() {
		var i ListAirportRow
		if err := rows.Scan(
			&i.ID,
			&i.IataCode,
			&i.Name,
			&i.City,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
