// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateAirlineCompany(ctx context.Context, arg CreateAirlineCompanyParams) (AirlineCompany, error)
	CreateAirport(ctx context.Context, arg CreateAirportParams) (AirportsDatum, error)
	DeleteAirlineCompany(ctx context.Context, companyID int64) error
	DeletedAirport(ctx context.Context, airportCode string) error
	GetAircraft(ctx context.Context, aircraftCode string) (AircraftsDatum, error)
	GetAirlineCompany(ctx context.Context, companyID int64) (AirlineCompany, error)
	GetAirport(ctx context.Context, airportCode string) (AirportsDatum, error)
	ListAircraft(ctx context.Context) ([]AircraftsDatum, error)
	ListAirlineCompany(ctx context.Context) ([]AirlineCompany, error)
	ListAirport(ctx context.Context) ([]ListAirportRow, error)
	UpdateAirport(ctx context.Context, airportCode string) (AirportsDatum, error)
}

var _ Querier = (*Queries)(nil)
