// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"time"
)

type Aircraft struct {
	// Aircraft code, IATA
	AircraftCode string
	// Aircraft model
	Model string
	// Maximal flying distance, km
	Range int32
}

// Aircrafts (internal data)
type AircraftsDatum struct {
	// Aircraft code, IATA
	AircraftCode string
	// Aircraft model
	Model string
	// Maximal flying distance, km
	Range     int32
	CompanyID int64
	CreatedAt time.Time
}

type AirlineCompany struct {
	CompanyID   int64
	CompanyName string
	IataCode    string
	MainAirport string
	CreatedAt   time.Time
}

type Airport struct {
	// Airport code
	AirportCode string
	// Airport name
	AirportName string
	// Country
	Country string
	// City
	City string
	// Airport coordinates (longitude and latitude)
	Coordinates interface{}
	Timezone    string
	CreatedAt   time.Time
}

// Airports (internal data)
type AirportsDatum struct {
	// Airport code
	AirportCode string
	// Airport name
	AirportName string
	// Country
	CountryCode string
	// City
	City string
	// Airport coordinates (longitude and latitude)
	Coordinates interface{}
	// Airport time zone
	Timezone string
	// time airport record Created
	CreatedAt time.Time
}
