DELETE  FROM aircrafts;
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'AT4','AT43', 'Aerospatiale/Alenia ATR 42-300 / 320', 619,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'AT5','AT45', 'Aerospatiale/Alenia ATR 42-500', 771,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'ATR','', 'Aerospatiale/Alenia ATR 42/ ATR 72', 769,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'AT7','AT72', 'Aerospatiale/Alenia ATR 72', 143,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'SSC','CONC', 'Aerospatiale/BAC Concorde', 539,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'AB3','A30B', 'Airbus A300 pax', 524,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'AB6','A306', 'Airbus A300-600 pax', 481,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '31F','A310', 'Airbus A310 Freighter', 366,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '310','A310', 'Airbus A310 all pax models', 734,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '31X','A310', 'Airbus A310-200 Freighter', 133,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '312','A310', 'Airbus A310-200 pax', 221,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '31Y','A310', 'Airbus A310-300 Freighter', 534,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '313','A310', 'Airbus A310-300 pax', 715,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '32S','', 'Airbus A318/319/320/321', 586,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '318','A318', 'Airbus A318', 387,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '319','A319', 'Airbus A319', 443,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '320','A320', 'Airbus A320-100/200', 189,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '321','A321', 'Airbus A321-100/200', 252,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '330','A330', 'Airbus A330 all models', 777,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '332','A332', 'Airbus A330-200', 557,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '333','A333', 'Airbus A330-300', 461,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '340','A340', 'Airbus A340 all models', 363,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '342','A342', 'Airbus A340-200', 293,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '343','A343', 'Airbus A340-300', 269,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '345','A345', 'Airbus A340-500', 161,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '346','A346', 'Airbus A340-600', 744,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '38F','', 'Airbus A380 Freighter', 186,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '380','', 'Airbus A380 pax', 300,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '388','', 'Airbus A380-800 pax', 533,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'A4F','A124', 'Antonov AN-124 Ruslan', 629,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'ANF','AN12', 'Antonov AN-12', 100,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'A40','A140', 'Antonov AN-140', 716,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'A30','AN30', 'Antonov AN-30', 622,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'A32','AN32', 'Antonov AN-32', 294,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'AR1','RJ1H', 'Avro RJ100 Avroliner', 353,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'AR7','RJ70', 'Avro RJ70 Avroliner', 692,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'ARJ','', 'Avro RJ70 RJ85 / RJ100 Avroliner', 331,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'AR8','RJ85', 'Avro RJ85 Avroliner', 211,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'AX1','RX1H', 'Avro RJX100', 116,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'ARX','', 'Avro RJX85 RJX100', 636,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '14F','', 'BAe 146 Freighter (-100/200/300QT)', 692,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '14X','B461', 'BAe 146 Freighter (-100QT & QC)', 596,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '14Y','B462', 'BAe 146 Freighter (-200QT & QC)', 389,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '14Z','B463', 'BAe 146 Freighter (-200QT & QC)', 665,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '146','', 'BAe 146 all pax models', 765,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '141','B461', 'BAe 146-100 Pax', 780,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '142','B462', 'BAe 146-200 Pax', 481,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '143','B463', 'BAe 146-300 Pax', 543,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '70M','B703', 'Boeing 707 Combi', 329,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '70F','B703', 'Boeing 707 Freighter', 471,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '703','B703', 'Boeing 707-300 pax', 366,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '707','', 'Boeing 707/720 all pax models', 653,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '717','B712', 'Boeing 717', 107,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '72M','', 'Boeing 727 Combi', 204,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '72F','', 'Boeing 727 Freighter (-100/200)', 584,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '727','', 'Boeing 727 all pax models', 408,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '72X','B721', 'Boeing 727-100 Freighter', 241,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '72B','B721', 'Boeing 727-100 Mixed Configuration', 415,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '721','B721', 'Boeing 727-100 pax', 636,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '72S','B722', 'Boeing 727-200 Advanced pax', 434,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '72Y','B722', 'Boeing 727-200 Freighter', 363,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '72C','B722', 'Boeing 727-200 Mixed Configuration', 153,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '722','B722', 'Boeing 727-200 pax', 723,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '73F','', 'Boeing 737 all Freighter models', 632,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '737','', 'Boeing 737 all pax models', 360,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '731','B731', 'Boeing 737-100 pax', 346,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '73M','B732', 'Boeing 737-200 Combi', 527,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '73X','B732', 'Boeing 737-200 Freighter', 713,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '732','B732', 'Boeing 737-200 pax', 450,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '73Y','B733', 'Boeing 737-300 Freighter', 296,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '733','B733', 'Boeing 737-300 pax', 739,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '734','B734', 'Boeing 737-400 pax', 128,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '735','B735', 'Boeing 737-500 pax', 275,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '736','B736', 'Boeing 737-600 pax', 646,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '73W','B737', 'Boeing 737-700 (winglets) pax', 264,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '73G','B737', 'Boeing 737-700 pax', 735,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '73H','B738', 'Boeing 737-800 (winglets) pax', 661,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '738','B738', 'Boeing 737-800 pax', 348,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '739','B739', 'Boeing 737-900 pax', 110,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '74M','', 'Boeing 747 all Combi models', 588,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '74F','', 'Boeing 747 all Freighter models', 571,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '747','', 'Boeing 747 all pax models', 215,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '74T','B741', 'Boeing 747-100 Freighter', 211,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '741','B741', 'Boeing 747-100 pax', 731,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '74C','B742', 'Boeing 747-200 Combi', 662,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '74X','B742', 'Boeing 747-200 Freighter', 764,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '742','B742', 'Boeing 747-200 pax', 172,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '74U','B743', 'Boeing 747-300 / 747-200 SUD Freighter', 324,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '74D','B743', 'Boeing 747-300 Combi', 205,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '743','B743', 'Boeing 747-300 pax', 202,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '74J','B744', 'Boeing 747-400 (Domestic) pax', 332,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '74E','B744', 'Boeing 747-400 Combi', 740,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '74Y','B744', 'Boeing 747-400 Freighter', 269,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '744','B744', 'Boeing 747-400 pax', 488,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '74L','N74S', 'Boeing 747SP', 167,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '74V','B74R', 'Boeing 747SR Freighter', 293,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '74R','B74R', 'Boeing 747SR pax', 500,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '75M','B752', 'Boeing 757 Mixed Configuration', 422,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '757','', 'Boeing 757 all pax models', 681,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '752','B752', 'Boeing 757-200 pax', 523,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '753','B753', 'Boeing 757-300 pax', 174,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '76F','', 'Boeing 767 all Freighter models', 799,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '767','', 'Boeing 767 all pax models', 448,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '76X','B762', 'Boeing 767-200 Freighter', 660,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '762','B762', 'Boeing 767-200 pax', 405,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '76Y','B763', 'Boeing 767-300 Freighter', 473,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '763','B763', 'Boeing 767-300 pax', 647,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '764','B764', 'Boeing 767-400 pax', 543,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '777','', 'Boeing 777 all pax models', 306,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '773','B773', 'Boeing 777-300 pax', 226,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'ATP','ATP', 'British Aerospace ATP', 569,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'JST','', 'British Aerospace Jetstream 31 32 41', 139,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'J31','JS31', 'British Aerospace Jetstream 31', 316,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'J41','JS41', 'British Aerospace Jetstream 41', 115,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'B12','BA11', 'British Aerospace One Eleven 200', 788,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'B13','BA11', 'British Aerospace One Eleven 300', 641,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'B14','BA11', 'British Aerospace One Eleven 400/475', 673,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'B15','BA11', 'British Aerospace One Eleven 500', 461,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'B11','BA11', 'British Aerospace One Eleven', 538,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'BNT','TRIS', 'Britten-Norman BN-2A Mk III Trislander', 532,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'CS2','C212', 'CASA / IPTN 212 Aviocar', 312,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'CS5','CN35', 'CASA / IPTN CN-235', 436,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'CL4','CL44', 'Canadair CL-44', 491,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'CCJ','CL60', 'Canadair Challenger', 419,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'CR1','CRJ1', 'Canadair Regional Jet 100', 648,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'CR2','CRJ2', 'Canadair Regional Jet 200', 244,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'CR7','CRJ7', 'Canadair Regional Jet 700', 227,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'CR9','CRJ9', 'Canadair Regional Jet 900', 745,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'CRJ','', 'Canadair Regional Jet', 636,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'DF2','', 'Dassault Falcon 10 100 20 200 2000', 718,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'DF3','', 'Dassault Falcon 50 900', 225,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'DFL','', 'Dassault Falcon', 182,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'DHD','DOVE', 'De Havilland DH.104 Dove', 641,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'DHH','HERN', 'De Havilland DH.114 Heron', 388,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'DHO','DHC3', 'De Havilland DHC-3 Otter Turbo Otter', 625,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'DHL','DHC3', 'De Havilland DHC-3 Turbo Otter', 616,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'DH7','DHC7', 'De Havilland DHC-7 Dash 7', 144,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'DH8','', 'De Havilland DHC-8 Dash 8 all models', 165,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'DH1','DH8A', 'De Havilland DHC-8-100 Dash 8 8Q', 670,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'DH2','DH8B', 'De Havilland DHC-8-200 Dash 8 8Q', 465,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'DH3','DH8C', 'De Havilland DHC-8-300 Dash 8 8Q', 608,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'DH4','DH8D', 'De Havilland DHC-8-400 Dash 8Q', 268,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'D1F','DC10', 'Douglas DC-10 all Freighters', 341,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'D10','DC10', 'Douglas DC-10 pax', 688,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'D1X','DC10', 'Douglas DC-10-10 Freighter', 598,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'D11','DC10', 'Douglas DC-10-10/15 pax', 427,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'D1Y','DC10', 'Douglas DC-10-30 / 40 Freighters', 159,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'D1C','DC10', 'Douglas DC-10-30/40 pax', 243,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'DC9','DC9', 'Douglas DC-9 all pax models', 689,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'D91','DC91', 'Douglas DC-9-10 pax', 176,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'D92','DC92', 'Douglas DC-9-20 pax', 391,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'D93','DC93', 'Douglas DC-9-30 pax', 157,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'D94','DC94', 'Douglas DC-9-40 pax', 560,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'D95','DC95', 'Douglas DC-9-50 pax', 606,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'EMJ','', 'Embraer 170/190', 791,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'E70','E170', 'Embraer 170', 546,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'E75','E175', 'Embraer 175', 759,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'E90','E190', 'Embraer 190', 479,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'E95','E195', 'Embraer 195', 176,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'EMB','E110', 'Embraer EMB.110 Bandeirnate', 422,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'EM2','E120', 'Embraer EMB.120 Brasilia', 295,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'ERJ','', 'Embraer RJ135 / RJ140 / RJ145', 513,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'ER3','E135', 'Embraer RJ135', 670,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'ERD','', 'Embraer RJ140', 571,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'ER4','E145', 'Embraer RJ145 Amazon', 672,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'MBH','B105', 'Eurocopter (MBB) Bo.105', 582,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'APH','', 'Eurocopter SA330 Puma/AS332 Super Puma', 207,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'NDH','S65C', 'Eurocopter SA365C SA365N Dauphin 2', 692,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'SWM','', 'Fairchild (Swearingen) SA26 SA226 SA227 Metro Merlin Expediter', 465,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'FRJ','J328', 'Fairchild Dornier 328JET', 138,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'D28','D228', 'Fairchild Dornier Do.228', 449,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'D38','D328', 'Fairchild Dornier Do.328', 206,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'F50','F50', 'Fokker 50', 289,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'F70','F70', 'Fokker 70', 137,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'F21','F28', 'Fokker F.28 Fellowship 1000', 402,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( '100','F100', 'Fokker F100', 789,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'GRG','G21', 'Grumman G.21 Goose', 405,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'GRJ','', 'Gulfstream G-1159 II III IV V', 375,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'ACP','AC68', 'Gulfstream/Rockwell Commander', 273,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'ACT','AC90', 'Gulfstream/Rockwell Turbo Commander', 416,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'ACD','', 'Gulfstream/Rockwell Turbo Commander', 351,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'H25','', 'Hawker Siddeley HS.125', 364,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'HS7','A748', 'Hawker Siddeley HS.748', 560,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'I14','I114', 'Ilyushin IL114', 201,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'I9M','IL96', 'Ilyushin IL96M pax', 654,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'L4T','L410', 'LET 410', 575,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'L11','L101', 'Lockheed L-1011 50 100 150 200 250', 459,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'L15','L101', 'Lockheed L-1011 500 Tristar pax', 269,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'L1F','L101', 'Lockheed L-1011 Tristar Freighter', 373,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'L10','L101', 'Lockheed L-1011 Tristar pax', 366,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'LOH','C130', 'Lockheed L-182 282 382 L-100 Hercules', 724,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'MIH','MI8', 'MIL Mi-8 / Mi-17 / Mi-171 / Mil-172', 381,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'M1F','MD11', 'McDonnell Douglas MD11 Freighter', 760,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'M1M','MD11', 'McDonnell Douglas MD11 Mixed Conf.', 508,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'M11','MD11', 'McDonnell Douglas MD11 pax', 790,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'M80','MD80', 'McDonnell Douglas MD80', 297,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'M81','MD81', 'McDonnell Douglas MD81', 507,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'M82','MD82', 'McDonnell Douglas MD82', 479,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'M83','MD83', 'McDonnell Douglas MD83', 115,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'M87','MD87', 'McDonnell Douglas MD87', 747,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'M88','MD88', 'McDonnell Douglas MD88', 799,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'M90','MD90', 'McDonnell Douglas MD90', 353,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'MU2','MU2', 'Mitsubishi Mu-2', 306,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'YS1','YS11', 'NAMC YS-11', 407,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'BES','B190', 'Raytheon Beechcraft 1900/1900C', 539,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'BEH','B190', 'Raytheon Beechcraft 1900D', 679,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'S20','SB20', 'Saab 2000', 480,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'SF3','SF34', 'Saab SF340A/B', 409,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'SHB','BELF', 'Shorts SC-5 Belfast', 263,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'SHS','SC7', 'Shorts SC-7 Skyvan', 505,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'SH3','SH33', 'Shorts SD.330', 192,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'SH6','SH36', 'Shorts SD.360', 514,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'S58','S58T', 'Sikorsky S-58T', 191,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'S61','S61', 'Sikorsky S-61', 549,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'S76','S76', 'Sikorsky S-76', 194,1);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'T20','T204', 'Tupolev Tu-204 / Tu-214', 190,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'TU3','T134', 'Tupolev Tu134', 647,2);
INSERT INTO aircrafts(iata_code, icao_code,  model, range, company_id)VALUES( 'TU5','T154', 'Tupolev Tu154', 567,2);
