// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: pb/airport.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Airport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AirportCode string                 `protobuf:"bytes,1,opt,name=airport_code,json=airportCode,proto3" json:"airport_code,omitempty"`
	AirportName string                 `protobuf:"bytes,2,opt,name=airport_name,json=airportName,proto3" json:"airport_name,omitempty"`
	CountryCode string                 `protobuf:"bytes,3,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	City        string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Coordinates string                 `protobuf:"bytes,5,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	Timezone    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timezone,proto3" json:"timezone,omitempty"`
}

func (x *Airport) Reset() {
	*x = Airport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_airport_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Airport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Airport) ProtoMessage() {}

func (x *Airport) ProtoReflect() protoreflect.Message {
	mi := &file_pb_airport_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Airport.ProtoReflect.Descriptor instead.
func (*Airport) Descriptor() ([]byte, []int) {
	return file_pb_airport_proto_rawDescGZIP(), []int{0}
}

func (x *Airport) GetAirportCode() string {
	if x != nil {
		return x.AirportCode
	}
	return ""
}

func (x *Airport) GetAirportName() string {
	if x != nil {
		return x.AirportName
	}
	return ""
}

func (x *Airport) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *Airport) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Airport) GetCoordinates() string {
	if x != nil {
		return x.Coordinates
	}
	return ""
}

func (x *Airport) GetTimezone() *timestamppb.Timestamp {
	if x != nil {
		return x.Timezone
	}
	return nil
}

type CreateAirportsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AirportCode string                 `protobuf:"bytes,1,opt,name=airport_code,json=airportCode,proto3" json:"airport_code,omitempty"`
	AirportName string                 `protobuf:"bytes,2,opt,name=airport_name,json=airportName,proto3" json:"airport_name,omitempty"`
	CountryCode string                 `protobuf:"bytes,3,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	City        string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Coordinates string                 `protobuf:"bytes,5,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	Timezone    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timezone,proto3" json:"timezone,omitempty"`
}

func (x *CreateAirportsRequest) Reset() {
	*x = CreateAirportsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_airport_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAirportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAirportsRequest) ProtoMessage() {}

func (x *CreateAirportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_airport_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAirportsRequest.ProtoReflect.Descriptor instead.
func (*CreateAirportsRequest) Descriptor() ([]byte, []int) {
	return file_pb_airport_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAirportsRequest) GetAirportCode() string {
	if x != nil {
		return x.AirportCode
	}
	return ""
}

func (x *CreateAirportsRequest) GetAirportName() string {
	if x != nil {
		return x.AirportName
	}
	return ""
}

func (x *CreateAirportsRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *CreateAirportsRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateAirportsRequest) GetCoordinates() string {
	if x != nil {
		return x.Coordinates
	}
	return ""
}

func (x *CreateAirportsRequest) GetTimezone() *timestamppb.Timestamp {
	if x != nil {
		return x.Timezone
	}
	return nil
}

type CreateAirportsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Airport []*Airport `protobuf:"bytes,1,rep,name=airport,proto3" json:"airport,omitempty"`
}

func (x *CreateAirportsReply) Reset() {
	*x = CreateAirportsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_airport_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAirportsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAirportsReply) ProtoMessage() {}

func (x *CreateAirportsReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_airport_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAirportsReply.ProtoReflect.Descriptor instead.
func (*CreateAirportsReply) Descriptor() ([]byte, []int) {
	return file_pb_airport_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAirportsReply) GetAirport() []*Airport {
	if x != nil {
		return x.Airport
	}
	return nil
}

type DeleteAirportsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AirportCode string `protobuf:"bytes,1,opt,name=airport_code,json=airportCode,proto3" json:"airport_code,omitempty"`
}

func (x *DeleteAirportsRequest) Reset() {
	*x = DeleteAirportsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_airport_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAirportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAirportsRequest) ProtoMessage() {}

func (x *DeleteAirportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_airport_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAirportsRequest.ProtoReflect.Descriptor instead.
func (*DeleteAirportsRequest) Descriptor() ([]byte, []int) {
	return file_pb_airport_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteAirportsRequest) GetAirportCode() string {
	if x != nil {
		return x.AirportCode
	}
	return ""
}

type DeleteAirportsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Airport *Airport `protobuf:"bytes,1,opt,name=airport,proto3" json:"airport,omitempty"`
}

func (x *DeleteAirportsReply) Reset() {
	*x = DeleteAirportsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_airport_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAirportsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAirportsReply) ProtoMessage() {}

func (x *DeleteAirportsReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_airport_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAirportsReply.ProtoReflect.Descriptor instead.
func (*DeleteAirportsReply) Descriptor() ([]byte, []int) {
	return file_pb_airport_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteAirportsReply) GetAirport() *Airport {
	if x != nil {
		return x.Airport
	}
	return nil
}

type GetAirportsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AirportCode string `protobuf:"bytes,1,opt,name=airport_code,json=airportCode,proto3" json:"airport_code,omitempty"`
}

func (x *GetAirportsRequest) Reset() {
	*x = GetAirportsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_airport_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAirportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAirportsRequest) ProtoMessage() {}

func (x *GetAirportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_airport_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAirportsRequest.ProtoReflect.Descriptor instead.
func (*GetAirportsRequest) Descriptor() ([]byte, []int) {
	return file_pb_airport_proto_rawDescGZIP(), []int{5}
}

func (x *GetAirportsRequest) GetAirportCode() string {
	if x != nil {
		return x.AirportCode
	}
	return ""
}

type GetAirportsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Airport []*Airport `protobuf:"bytes,1,rep,name=airport,proto3" json:"airport,omitempty"`
}

func (x *GetAirportsReply) Reset() {
	*x = GetAirportsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_airport_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAirportsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAirportsReply) ProtoMessage() {}

func (x *GetAirportsReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_airport_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAirportsReply.ProtoReflect.Descriptor instead.
func (*GetAirportsReply) Descriptor() ([]byte, []int) {
	return file_pb_airport_proto_rawDescGZIP(), []int{6}
}

func (x *GetAirportsReply) GetAirport() []*Airport {
	if x != nil {
		return x.Airport
	}
	return nil
}

type ListAirportsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAirportsRequest) Reset() {
	*x = ListAirportsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_airport_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAirportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAirportsRequest) ProtoMessage() {}

func (x *ListAirportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_airport_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAirportsRequest.ProtoReflect.Descriptor instead.
func (*ListAirportsRequest) Descriptor() ([]byte, []int) {
	return file_pb_airport_proto_rawDescGZIP(), []int{7}
}

type ListAirportsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Airport []*Airport `protobuf:"bytes,1,rep,name=airport,proto3" json:"airport,omitempty"`
}

func (x *ListAirportsReply) Reset() {
	*x = ListAirportsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_airport_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAirportsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAirportsReply) ProtoMessage() {}

func (x *ListAirportsReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_airport_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAirportsReply.ProtoReflect.Descriptor instead.
func (*ListAirportsReply) Descriptor() ([]byte, []int) {
	return file_pb_airport_proto_rawDescGZIP(), []int{8}
}

func (x *ListAirportsReply) GetAirport() []*Airport {
	if x != nil {
		return x.Airport
	}
	return nil
}

var File_pb_airport_proto protoreflect.FileDescriptor

var file_pb_airport_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x62, 0x2f, 0x61, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe0, 0x01, 0x0a, 0x07, 0x41, 0x69, 0x72, 0x70,
	0x6f, 0x72, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x69, 0x72, 0x70, 0x6f,
	0x72, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x69, 0x72, 0x70, 0x6f, 0x72,
	0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x69,
	0x72, 0x70, 0x6f, 0x72, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79,
	0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74,
	0x65, 0x73, 0x12, 0x36, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x22, 0xee, 0x01, 0x0a, 0x15, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x69, 0x72, 0x70,
	0x6f, 0x72, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x69, 0x72, 0x70, 0x6f,
	0x72, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61,
	0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74,
	0x79, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61,
	0x74, 0x65, 0x73, 0x12, 0x36, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x22, 0x3c, 0x0a, 0x13, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x25, 0x0a, 0x07, 0x61, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74,
	0x52, 0x07, 0x61, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x3a, 0x0a, 0x15, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x69, 0x72, 0x70, 0x6f, 0x72,
	0x74, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x3c, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41,
	0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x25, 0x0a, 0x07,
	0x61, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x70, 0x62, 0x2e, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x07, 0x61, 0x69, 0x72, 0x70,
	0x6f, 0x72, 0x74, 0x22, 0x37, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x69, 0x72,
	0x70, 0x6f, 0x72, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x61, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x39, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x25, 0x0a, 0x07, 0x61, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x07,
	0x61, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x41,
	0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3a,
	0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x25, 0x0a, 0x07, 0x61, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72,
	0x74, 0x52, 0x07, 0x61, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x32, 0x99, 0x02, 0x0a, 0x0e, 0x41,
	0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a,
	0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x12,
	0x19, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x69, 0x72, 0x70, 0x6f,
	0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x44, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x69, 0x72,
	0x70, 0x6f, 0x72, 0x74, 0x73, 0x12, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x69, 0x72, 0x70,
	0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3b, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3e, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x69,
	0x72, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x15, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_airport_proto_rawDescOnce sync.Once
	file_pb_airport_proto_rawDescData = file_pb_airport_proto_rawDesc
)

func file_pb_airport_proto_rawDescGZIP() []byte {
	file_pb_airport_proto_rawDescOnce.Do(func() {
		file_pb_airport_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_airport_proto_rawDescData)
	})
	return file_pb_airport_proto_rawDescData
}

var file_pb_airport_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pb_airport_proto_goTypes = []interface{}{
	(*Airport)(nil),               // 0: pb.Airport
	(*CreateAirportsRequest)(nil), // 1: pb.CreateAirportsRequest
	(*CreateAirportsReply)(nil),   // 2: pb.CreateAirportsReply
	(*DeleteAirportsRequest)(nil), // 3: pb.DeleteAirportsRequest
	(*DeleteAirportsReply)(nil),   // 4: pb.DeleteAirportsReply
	(*GetAirportsRequest)(nil),    // 5: pb.GetAirportsRequest
	(*GetAirportsReply)(nil),      // 6: pb.GetAirportsReply
	(*ListAirportsRequest)(nil),   // 7: pb.ListAirportsRequest
	(*ListAirportsReply)(nil),     // 8: pb.ListAirportsReply
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_pb_airport_proto_depIdxs = []int32{
	9,  // 0: pb.Airport.timezone:type_name -> google.protobuf.Timestamp
	9,  // 1: pb.CreateAirportsRequest.timezone:type_name -> google.protobuf.Timestamp
	0,  // 2: pb.CreateAirportsReply.airport:type_name -> pb.Airport
	0,  // 3: pb.DeleteAirportsReply.airport:type_name -> pb.Airport
	0,  // 4: pb.GetAirportsReply.airport:type_name -> pb.Airport
	0,  // 5: pb.ListAirportsReply.airport:type_name -> pb.Airport
	1,  // 6: pb.AirportService.CreateAirports:input_type -> pb.CreateAirportsRequest
	3,  // 7: pb.AirportService.DeleteAirports:input_type -> pb.DeleteAirportsRequest
	5,  // 8: pb.AirportService.GetAirports:input_type -> pb.GetAirportsRequest
	7,  // 9: pb.AirportService.ListAirports:input_type -> pb.ListAirportsRequest
	2,  // 10: pb.AirportService.CreateAirports:output_type -> pb.CreateAirportsReply
	4,  // 11: pb.AirportService.DeleteAirports:output_type -> pb.DeleteAirportsReply
	6,  // 12: pb.AirportService.GetAirports:output_type -> pb.GetAirportsReply
	8,  // 13: pb.AirportService.ListAirports:output_type -> pb.ListAirportsReply
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pb_airport_proto_init() }
func file_pb_airport_proto_init() {
	if File_pb_airport_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_airport_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Airport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_airport_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAirportsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_airport_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAirportsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_airport_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAirportsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_airport_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAirportsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_airport_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAirportsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_airport_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAirportsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_airport_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAirportsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_airport_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAirportsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_airport_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_airport_proto_goTypes,
		DependencyIndexes: file_pb_airport_proto_depIdxs,
		MessageInfos:      file_pb_airport_proto_msgTypes,
	}.Build()
	File_pb_airport_proto = out.File
	file_pb_airport_proto_rawDesc = nil
	file_pb_airport_proto_goTypes = nil
	file_pb_airport_proto_depIdxs = nil
}
