// Code generated by sqlc. DO NOT EDIT.

package s

import (
	"time"
)

type Airport struct {
	// Airport code
	AirportCode string
	// Airport name
	AirportName string
	// Country
	Country string
	// City
	City string
	// Airport coordinates (longitude and latitude)
	Coordinates interface{}
	Timezone    string
	CreatedAt   time.Time
}

// Airports (internal data)
type AirportsDatum struct {
	// Airport code
	AirportCode string
	// Airport name
	AirportName string
	// Country
	CountryCode string
	// City
	City string
	// Airport coordinates (longitude and latitude)
	Coordinates interface{}
	// Airport time zone
	Timezone string
	// time airport record Created
	CreatedAt time.Time
}
