// Code generated by sqlc. DO NOT EDIT.

package s

import (
	"context"
)

type Querier interface {
	CreateAirport(ctx context.Context, arg CreateAirportParams) (AirportsDatum, error)
	DeletedAirport(ctx context.Context, airportCode string) error
	GetAirport(ctx context.Context, airportCode string) (AirportsDatum, error)
	ListAirport(ctx context.Context) ([]ListAirportRow, error)
	UpdateAirport(ctx context.Context, airportCode string) (AirportsDatum, error)
}

var _ Querier = (*Queries)(nil)
