// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/flightinfo.proto

package flightinfo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Flightinfo service

func NewFlightinfoEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Flightinfo service

type FlightinfoService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Flightinfo_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Flightinfo_PingPongService, error)
}

type flightinfoService struct {
	c    client.Client
	name string
}

func NewFlightinfoService(name string, c client.Client) FlightinfoService {
	return &flightinfoService{
		c:    c,
		name: name,
	}
}

func (c *flightinfoService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Flightinfo.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightinfoService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Flightinfo_StreamService, error) {
	req := c.c.NewRequest(c.name, "Flightinfo.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &flightinfoServiceStream{stream}, nil
}

type Flightinfo_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type flightinfoServiceStream struct {
	stream client.Stream
}

func (x *flightinfoServiceStream) Close() error {
	return x.stream.Close()
}

func (x *flightinfoServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *flightinfoServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *flightinfoServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *flightinfoServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *flightinfoService) PingPong(ctx context.Context, opts ...client.CallOption) (Flightinfo_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Flightinfo.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &flightinfoServicePingPong{stream}, nil
}

type Flightinfo_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type flightinfoServicePingPong struct {
	stream client.Stream
}

func (x *flightinfoServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *flightinfoServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *flightinfoServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *flightinfoServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *flightinfoServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *flightinfoServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Flightinfo service

type FlightinfoHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Flightinfo_StreamStream) error
	PingPong(context.Context, Flightinfo_PingPongStream) error
}

func RegisterFlightinfoHandler(s server.Server, hdlr FlightinfoHandler, opts ...server.HandlerOption) error {
	type flightinfo interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Flightinfo struct {
		flightinfo
	}
	h := &flightinfoHandler{hdlr}
	return s.Handle(s.NewHandler(&Flightinfo{h}, opts...))
}

type flightinfoHandler struct {
	FlightinfoHandler
}

func (h *flightinfoHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.FlightinfoHandler.Call(ctx, in, out)
}

func (h *flightinfoHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.FlightinfoHandler.Stream(ctx, m, &flightinfoStreamStream{stream})
}

type Flightinfo_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type flightinfoStreamStream struct {
	stream server.Stream
}

func (x *flightinfoStreamStream) Close() error {
	return x.stream.Close()
}

func (x *flightinfoStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *flightinfoStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *flightinfoStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *flightinfoStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *flightinfoHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.FlightinfoHandler.PingPong(ctx, &flightinfoPingPongStream{stream})
}

type Flightinfo_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type flightinfoPingPongStream struct {
	stream server.Stream
}

func (x *flightinfoPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *flightinfoPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *flightinfoPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *flightinfoPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *flightinfoPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *flightinfoPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
