// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: srv_airline.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AirlinesServiceClient is the client API for AirlinesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AirlinesServiceClient interface {
	// Airlines Service RPC
	CreateAirline(ctx context.Context, in *CreateAirlineRequest, opts ...grpc.CallOption) (*CreateAirlineResponse, error)
	ShowAirline(ctx context.Context, in *GetAirlineRequest, opts ...grpc.CallOption) (*GetAirlineResponse, error)
	UpdateAirline(ctx context.Context, in *UpdateAirlineRequest, opts ...grpc.CallOption) (*UpdateAirlineResponse, error)
	DeleteAirline(ctx context.Context, in *DeleteAirlineRequest, opts ...grpc.CallOption) (*DeleteAirlineResponse, error)
	ListAirlines(ctx context.Context, in *ListAirlinesReq, opts ...grpc.CallOption) (*ListAirlineRes, error)
	CreateAirport(ctx context.Context, in *CreateAirportRequest, opts ...grpc.CallOption) (*CreateAirportResponse, error)
	ShowAirport(ctx context.Context, in *GetAirportRequest, opts ...grpc.CallOption) (*GetAirportResponse, error)
	UpdateAirport(ctx context.Context, in *UpdateAirportRequest, opts ...grpc.CallOption) (*UpdateAirportResponse, error)
	DeleteAirport(ctx context.Context, in *DeleteAirportRequest, opts ...grpc.CallOption) (*DeleteAirportResponse, error)
	ListAirports(ctx context.Context, in *ListAirportRequest, opts ...grpc.CallOption) (*ListAirportResponse, error)
}

type airlinesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAirlinesServiceClient(cc grpc.ClientConnInterface) AirlinesServiceClient {
	return &airlinesServiceClient{cc}
}

func (c *airlinesServiceClient) CreateAirline(ctx context.Context, in *CreateAirlineRequest, opts ...grpc.CallOption) (*CreateAirlineResponse, error) {
	out := new(CreateAirlineResponse)
	err := c.cc.Invoke(ctx, "/pb.AirlinesService/CreateAirline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airlinesServiceClient) ShowAirline(ctx context.Context, in *GetAirlineRequest, opts ...grpc.CallOption) (*GetAirlineResponse, error) {
	out := new(GetAirlineResponse)
	err := c.cc.Invoke(ctx, "/pb.AirlinesService/ShowAirline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airlinesServiceClient) UpdateAirline(ctx context.Context, in *UpdateAirlineRequest, opts ...grpc.CallOption) (*UpdateAirlineResponse, error) {
	out := new(UpdateAirlineResponse)
	err := c.cc.Invoke(ctx, "/pb.AirlinesService/UpdateAirline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airlinesServiceClient) DeleteAirline(ctx context.Context, in *DeleteAirlineRequest, opts ...grpc.CallOption) (*DeleteAirlineResponse, error) {
	out := new(DeleteAirlineResponse)
	err := c.cc.Invoke(ctx, "/pb.AirlinesService/DeleteAirline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airlinesServiceClient) ListAirlines(ctx context.Context, in *ListAirlinesReq, opts ...grpc.CallOption) (*ListAirlineRes, error) {
	out := new(ListAirlineRes)
	err := c.cc.Invoke(ctx, "/pb.AirlinesService/ListAirlines", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airlinesServiceClient) CreateAirport(ctx context.Context, in *CreateAirportRequest, opts ...grpc.CallOption) (*CreateAirportResponse, error) {
	out := new(CreateAirportResponse)
	err := c.cc.Invoke(ctx, "/pb.AirlinesService/CreateAirport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airlinesServiceClient) ShowAirport(ctx context.Context, in *GetAirportRequest, opts ...grpc.CallOption) (*GetAirportResponse, error) {
	out := new(GetAirportResponse)
	err := c.cc.Invoke(ctx, "/pb.AirlinesService/ShowAirport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airlinesServiceClient) UpdateAirport(ctx context.Context, in *UpdateAirportRequest, opts ...grpc.CallOption) (*UpdateAirportResponse, error) {
	out := new(UpdateAirportResponse)
	err := c.cc.Invoke(ctx, "/pb.AirlinesService/UpdateAirport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airlinesServiceClient) DeleteAirport(ctx context.Context, in *DeleteAirportRequest, opts ...grpc.CallOption) (*DeleteAirportResponse, error) {
	out := new(DeleteAirportResponse)
	err := c.cc.Invoke(ctx, "/pb.AirlinesService/DeleteAirport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airlinesServiceClient) ListAirports(ctx context.Context, in *ListAirportRequest, opts ...grpc.CallOption) (*ListAirportResponse, error) {
	out := new(ListAirportResponse)
	err := c.cc.Invoke(ctx, "/pb.AirlinesService/ListAirports", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AirlinesServiceServer is the server API for AirlinesService service.
// All implementations must embed UnimplementedAirlinesServiceServer
// for forward compatibility
type AirlinesServiceServer interface {
	// Airlines Service RPC
	CreateAirline(context.Context, *CreateAirlineRequest) (*CreateAirlineResponse, error)
	ShowAirline(context.Context, *GetAirlineRequest) (*GetAirlineResponse, error)
	UpdateAirline(context.Context, *UpdateAirlineRequest) (*UpdateAirlineResponse, error)
	DeleteAirline(context.Context, *DeleteAirlineRequest) (*DeleteAirlineResponse, error)
	ListAirlines(context.Context, *ListAirlinesReq) (*ListAirlineRes, error)
	CreateAirport(context.Context, *CreateAirportRequest) (*CreateAirportResponse, error)
	ShowAirport(context.Context, *GetAirportRequest) (*GetAirportResponse, error)
	UpdateAirport(context.Context, *UpdateAirportRequest) (*UpdateAirportResponse, error)
	DeleteAirport(context.Context, *DeleteAirportRequest) (*DeleteAirportResponse, error)
	ListAirports(context.Context, *ListAirportRequest) (*ListAirportResponse, error)
	mustEmbedUnimplementedAirlinesServiceServer()
}

// UnimplementedAirlinesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAirlinesServiceServer struct {
}

func (UnimplementedAirlinesServiceServer) CreateAirline(context.Context, *CreateAirlineRequest) (*CreateAirlineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAirline not implemented")
}
func (UnimplementedAirlinesServiceServer) ShowAirline(context.Context, *GetAirlineRequest) (*GetAirlineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowAirline not implemented")
}
func (UnimplementedAirlinesServiceServer) UpdateAirline(context.Context, *UpdateAirlineRequest) (*UpdateAirlineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAirline not implemented")
}
func (UnimplementedAirlinesServiceServer) DeleteAirline(context.Context, *DeleteAirlineRequest) (*DeleteAirlineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAirline not implemented")
}
func (UnimplementedAirlinesServiceServer) ListAirlines(context.Context, *ListAirlinesReq) (*ListAirlineRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAirlines not implemented")
}
func (UnimplementedAirlinesServiceServer) CreateAirport(context.Context, *CreateAirportRequest) (*CreateAirportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAirport not implemented")
}
func (UnimplementedAirlinesServiceServer) ShowAirport(context.Context, *GetAirportRequest) (*GetAirportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowAirport not implemented")
}
func (UnimplementedAirlinesServiceServer) UpdateAirport(context.Context, *UpdateAirportRequest) (*UpdateAirportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAirport not implemented")
}
func (UnimplementedAirlinesServiceServer) DeleteAirport(context.Context, *DeleteAirportRequest) (*DeleteAirportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAirport not implemented")
}
func (UnimplementedAirlinesServiceServer) ListAirports(context.Context, *ListAirportRequest) (*ListAirportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAirports not implemented")
}
func (UnimplementedAirlinesServiceServer) mustEmbedUnimplementedAirlinesServiceServer() {}

// UnsafeAirlinesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AirlinesServiceServer will
// result in compilation errors.
type UnsafeAirlinesServiceServer interface {
	mustEmbedUnimplementedAirlinesServiceServer()
}

func RegisterAirlinesServiceServer(s grpc.ServiceRegistrar, srv AirlinesServiceServer) {
	s.RegisterService(&AirlinesService_ServiceDesc, srv)
}

func _AirlinesService_CreateAirline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAirlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirlinesServiceServer).CreateAirline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AirlinesService/CreateAirline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirlinesServiceServer).CreateAirline(ctx, req.(*CreateAirlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirlinesService_ShowAirline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAirlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirlinesServiceServer).ShowAirline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AirlinesService/ShowAirline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirlinesServiceServer).ShowAirline(ctx, req.(*GetAirlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirlinesService_UpdateAirline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAirlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirlinesServiceServer).UpdateAirline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AirlinesService/UpdateAirline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirlinesServiceServer).UpdateAirline(ctx, req.(*UpdateAirlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirlinesService_DeleteAirline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAirlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirlinesServiceServer).DeleteAirline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AirlinesService/DeleteAirline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirlinesServiceServer).DeleteAirline(ctx, req.(*DeleteAirlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirlinesService_ListAirlines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAirlinesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirlinesServiceServer).ListAirlines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AirlinesService/ListAirlines",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirlinesServiceServer).ListAirlines(ctx, req.(*ListAirlinesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirlinesService_CreateAirport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAirportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirlinesServiceServer).CreateAirport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AirlinesService/CreateAirport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirlinesServiceServer).CreateAirport(ctx, req.(*CreateAirportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirlinesService_ShowAirport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAirportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirlinesServiceServer).ShowAirport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AirlinesService/ShowAirport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirlinesServiceServer).ShowAirport(ctx, req.(*GetAirportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirlinesService_UpdateAirport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAirportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirlinesServiceServer).UpdateAirport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AirlinesService/UpdateAirport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirlinesServiceServer).UpdateAirport(ctx, req.(*UpdateAirportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirlinesService_DeleteAirport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAirportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirlinesServiceServer).DeleteAirport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AirlinesService/DeleteAirport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirlinesServiceServer).DeleteAirport(ctx, req.(*DeleteAirportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirlinesService_ListAirports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAirportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirlinesServiceServer).ListAirports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AirlinesService/ListAirports",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirlinesServiceServer).ListAirports(ctx, req.(*ListAirportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AirlinesService_ServiceDesc is the grpc.ServiceDesc for AirlinesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AirlinesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AirlinesService",
	HandlerType: (*AirlinesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAirline",
			Handler:    _AirlinesService_CreateAirline_Handler,
		},
		{
			MethodName: "ShowAirline",
			Handler:    _AirlinesService_ShowAirline_Handler,
		},
		{
			MethodName: "UpdateAirline",
			Handler:    _AirlinesService_UpdateAirline_Handler,
		},
		{
			MethodName: "DeleteAirline",
			Handler:    _AirlinesService_DeleteAirline_Handler,
		},
		{
			MethodName: "ListAirlines",
			Handler:    _AirlinesService_ListAirlines_Handler,
		},
		{
			MethodName: "CreateAirport",
			Handler:    _AirlinesService_CreateAirport_Handler,
		},
		{
			MethodName: "ShowAirport",
			Handler:    _AirlinesService_ShowAirport_Handler,
		},
		{
			MethodName: "UpdateAirport",
			Handler:    _AirlinesService_UpdateAirport_Handler,
		},
		{
			MethodName: "DeleteAirport",
			Handler:    _AirlinesService_DeleteAirport_Handler,
		},
		{
			MethodName: "ListAirports",
			Handler:    _AirlinesService_ListAirports_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "srv_airline.proto",
}
