name: Generate Go code with sqlc

on:
  push:
    branches:
      - main  # or the branch where you want this action to run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'sqlc'  # checkout sqlc branch

    - name: Set up sqlc
      uses: sqlc-dev/setup-sqlc@v4
      with:
        sqlc-version: '1.21.0'

    - name: Generate Go code
      run: sqlc generate

    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Generate Go code with sqlc" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.head_ref }}
