name: Generate Go code with sqlc

on:
  push:
    branches:
      - sqlc  
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'sqlc'  # checkout sqlc branch

    - name: Set up sqlc
      uses: sqlc-dev/setup-sqlc@v4
      with:
        sqlc-version: '1.21.0'

    - name: Generate Go code
      run: sqlc generate

    
    
    - name: Commit and push
      uses: actions/github-script@v3
      with:
          script: |
           const exec = require('@actions/exec');
           await exec.exec('git config --local user.email "action@github.com"');
           await exec.exec('git config --local user.name "GitHub Action"');
           await exec.exec('git add .');
           await exec.exec('git commit -m "Generate Go code with sqlc" -a');
            await exec.exec('git push');


