name: Generate Go code with sqlc

on:
  push:
    branches: [ dev, sqlc ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'sqlc'  # checkout sqlc branch

    - name: Set up sqlc
      uses: sqlc-dev/setup-sqlc@v4
      with:
        sqlc-version: '1.21.0'

    - name: Generate Go code from Sql files 
      run: sqlc generate

  revert:
    runs-on: ubuntu-latest
    needs: build

    steps: 
    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        ref: '${{ github.event.inputs.branch }}'
        fetch-depth: 0

    - name: Revert pushed commit
      run: | 
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git revert --no-edit HEAD
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}		
      



# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@master
#       with:
#         persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
#         fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
#     - name: Create local changes
#       run: |
#         ...
#     - name: Commit & Push changes
#       uses: actions-js/push@master
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}		
