// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/niiniyare/awo/db/sqlc (interfaces: Querier)

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	db "github.com/niiniyare/awo/db/sqlc"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// CreateAircraft mocks base method.
func (m *MockQuerier) CreateAircraft(arg0 context.Context, arg1 db.CreateAircraftParams) (db.Aircraft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAircraft", arg0, arg1)
	ret0, _ := ret[0].(db.Aircraft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAircraft indicates an expected call of CreateAircraft.
func (mr *MockQuerierMockRecorder) CreateAircraft(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAircraft", reflect.TypeOf((*MockQuerier)(nil).CreateAircraft), arg0, arg1)
}

// CreateAirline mocks base method.
func (m *MockQuerier) CreateAirline(arg0 context.Context, arg1 db.CreateAirlineParams) (db.Airline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAirline", arg0, arg1)
	ret0, _ := ret[0].(db.Airline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAirline indicates an expected call of CreateAirline.
func (mr *MockQuerierMockRecorder) CreateAirline(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAirline", reflect.TypeOf((*MockQuerier)(nil).CreateAirline), arg0, arg1)
}

// CreateAirport mocks base method.
func (m *MockQuerier) CreateAirport(arg0 context.Context, arg1 db.CreateAirportParams) (db.Airport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAirport", arg0, arg1)
	ret0, _ := ret[0].(db.Airport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAirport indicates an expected call of CreateAirport.
func (mr *MockQuerierMockRecorder) CreateAirport(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAirport", reflect.TypeOf((*MockQuerier)(nil).CreateAirport), arg0, arg1)
}

// DeleteAircraft mocks base method.
func (m *MockQuerier) DeleteAircraft(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAircraft", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAircraft indicates an expected call of DeleteAircraft.
func (mr *MockQuerierMockRecorder) DeleteAircraft(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAircraft", reflect.TypeOf((*MockQuerier)(nil).DeleteAircraft), arg0, arg1)
}

// DeleteAirline mocks base method.
func (m *MockQuerier) DeleteAirline(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAirline", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAirline indicates an expected call of DeleteAirline.
func (mr *MockQuerierMockRecorder) DeleteAirline(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAirline", reflect.TypeOf((*MockQuerier)(nil).DeleteAirline), arg0, arg1)
}

// DeleteAirports mocks base method.
func (m *MockQuerier) DeleteAirports(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAirports", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAirports indicates an expected call of DeleteAirports.
func (mr *MockQuerierMockRecorder) DeleteAirports(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAirports", reflect.TypeOf((*MockQuerier)(nil).DeleteAirports), arg0, arg1)
}

// GetAircraft mocks base method.
func (m *MockQuerier) GetAircraft(arg0 context.Context, arg1 int64) (db.Aircraft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAircraft", arg0, arg1)
	ret0, _ := ret[0].(db.Aircraft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAircraft indicates an expected call of GetAircraft.
func (mr *MockQuerierMockRecorder) GetAircraft(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAircraft", reflect.TypeOf((*MockQuerier)(nil).GetAircraft), arg0, arg1)
}

// GetAirline mocks base method.
func (m *MockQuerier) GetAirline(arg0 context.Context, arg1 int64) (db.Airline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAirline", arg0, arg1)
	ret0, _ := ret[0].(db.Airline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAirline indicates an expected call of GetAirline.
func (mr *MockQuerierMockRecorder) GetAirline(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAirline", reflect.TypeOf((*MockQuerier)(nil).GetAirline), arg0, arg1)
}

// GetAirports mocks base method.
func (m *MockQuerier) GetAirports(arg0 context.Context, arg1 string) (db.Airport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAirports", arg0, arg1)
	ret0, _ := ret[0].(db.Airport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAirports indicates an expected call of GetAirports.
func (mr *MockQuerierMockRecorder) GetAirports(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAirports", reflect.TypeOf((*MockQuerier)(nil).GetAirports), arg0, arg1)
}

// ListAircraft mocks base method.
func (m *MockQuerier) ListAircraft(arg0 context.Context, arg1 db.ListAircraftParams) ([]db.Aircraft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAircraft", arg0, arg1)
	ret0, _ := ret[0].([]db.Aircraft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAircraft indicates an expected call of ListAircraft.
func (mr *MockQuerierMockRecorder) ListAircraft(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAircraft", reflect.TypeOf((*MockQuerier)(nil).ListAircraft), arg0, arg1)
}

// ListAirline mocks base method.
func (m *MockQuerier) ListAirline(arg0 context.Context, arg1 db.ListAirlineParams) ([]db.Airline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAirline", arg0, arg1)
	ret0, _ := ret[0].([]db.Airline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAirline indicates an expected call of ListAirline.
func (mr *MockQuerierMockRecorder) ListAirline(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAirline", reflect.TypeOf((*MockQuerier)(nil).ListAirline), arg0, arg1)
}

// ListAirports mocks base method.
func (m *MockQuerier) ListAirports(arg0 context.Context) ([]db.ListAirportsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAirports", arg0)
	ret0, _ := ret[0].([]db.ListAirportsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAirports indicates an expected call of ListAirports.
func (mr *MockQuerierMockRecorder) ListAirports(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAirports", reflect.TypeOf((*MockQuerier)(nil).ListAirports), arg0)
}
