// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/niiniyare/awo/db/sqlc (interfaces: Store)

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	db "github.com/niiniyare/awo/db/sqlc"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateAircraft mocks base method.
func (m *MockStore) CreateAircraft(arg0 context.Context, arg1 db.CreateAircraftParams) (db.AircraftsDatum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAircraft", arg0, arg1)
	ret0, _ := ret[0].(db.AircraftsDatum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAircraft indicates an expected call of CreateAircraft.
func (mr *MockStoreMockRecorder) CreateAircraft(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAircraft", reflect.TypeOf((*MockStore)(nil).CreateAircraft), arg0, arg1)
}

// CreateAirlineCompany mocks base method.
func (m *MockStore) CreateAirlineCompany(arg0 context.Context, arg1 db.CreateAirlineCompanyParams) (db.AirlineCompany, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAirlineCompany", arg0, arg1)
	ret0, _ := ret[0].(db.AirlineCompany)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAirlineCompany indicates an expected call of CreateAirlineCompany.
func (mr *MockStoreMockRecorder) CreateAirlineCompany(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAirlineCompany", reflect.TypeOf((*MockStore)(nil).CreateAirlineCompany), arg0, arg1)
}

// CreateAirportList mocks base method.
func (m *MockStore) CreateAirportList(arg0 context.Context, arg1 db.CreateAirportListParams) ([]db.AirportsDatum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAirportList", arg0, arg1)
	ret0, _ := ret[0].([]db.AirportsDatum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAirportList indicates an expected call of CreateAirportList.
func (mr *MockStoreMockRecorder) CreateAirportList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAirportList", reflect.TypeOf((*MockStore)(nil).CreateAirportList), arg0, arg1)
}

// CreateAirports mocks base method.
func (m *MockStore) CreateAirports(arg0 context.Context, arg1 db.CreateAirportsParams) (db.AirportsDatum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAirports", arg0, arg1)
	ret0, _ := ret[0].(db.AirportsDatum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAirports indicates an expected call of CreateAirports.
func (mr *MockStoreMockRecorder) CreateAirports(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAirports", reflect.TypeOf((*MockStore)(nil).CreateAirports), arg0, arg1)
}

// DeleteAircraft mocks base method.
func (m *MockStore) DeleteAircraft(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAircraft", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAircraft indicates an expected call of DeleteAircraft.
func (mr *MockStoreMockRecorder) DeleteAircraft(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAircraft", reflect.TypeOf((*MockStore)(nil).DeleteAircraft), arg0, arg1)
}

// DeleteAirlineCompany mocks base method.
func (m *MockStore) DeleteAirlineCompany(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAirlineCompany", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAirlineCompany indicates an expected call of DeleteAirlineCompany.
func (mr *MockStoreMockRecorder) DeleteAirlineCompany(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAirlineCompany", reflect.TypeOf((*MockStore)(nil).DeleteAirlineCompany), arg0, arg1)
}

// DeleteAirports mocks base method.
func (m *MockStore) DeleteAirports(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAirports", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAirports indicates an expected call of DeleteAirports.
func (mr *MockStoreMockRecorder) DeleteAirports(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAirports", reflect.TypeOf((*MockStore)(nil).DeleteAirports), arg0, arg1)
}

// GetAircraft mocks base method.
func (m *MockStore) GetAircraft(arg0 context.Context, arg1 string) (db.AircraftsDatum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAircraft", arg0, arg1)
	ret0, _ := ret[0].(db.AircraftsDatum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAircraft indicates an expected call of GetAircraft.
func (mr *MockStoreMockRecorder) GetAircraft(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAircraft", reflect.TypeOf((*MockStore)(nil).GetAircraft), arg0, arg1)
}

// GetAirlineCompany mocks base method.
func (m *MockStore) GetAirlineCompany(arg0 context.Context, arg1 int64) (db.AirlineCompany, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAirlineCompany", arg0, arg1)
	ret0, _ := ret[0].(db.AirlineCompany)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAirlineCompany indicates an expected call of GetAirlineCompany.
func (mr *MockStoreMockRecorder) GetAirlineCompany(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAirlineCompany", reflect.TypeOf((*MockStore)(nil).GetAirlineCompany), arg0, arg1)
}

// GetAirports mocks base method.
func (m *MockStore) GetAirports(arg0 context.Context, arg1 string) (db.AirportsDatum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAirports", arg0, arg1)
	ret0, _ := ret[0].(db.AirportsDatum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAirports indicates an expected call of GetAirports.
func (mr *MockStoreMockRecorder) GetAirports(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAirports", reflect.TypeOf((*MockStore)(nil).GetAirports), arg0, arg1)
}

// ListAircraft mocks base method.
func (m *MockStore) ListAircraft(arg0 context.Context) ([]db.AircraftsDatum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAircraft", arg0)
	ret0, _ := ret[0].([]db.AircraftsDatum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAircraft indicates an expected call of ListAircraft.
func (mr *MockStoreMockRecorder) ListAircraft(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAircraft", reflect.TypeOf((*MockStore)(nil).ListAircraft), arg0)
}

// ListAirlineCompany mocks base method.
func (m *MockStore) ListAirlineCompany(arg0 context.Context) ([]db.AirlineCompany, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAirlineCompany", arg0)
	ret0, _ := ret[0].([]db.AirlineCompany)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAirlineCompany indicates an expected call of ListAirlineCompany.
func (mr *MockStoreMockRecorder) ListAirlineCompany(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAirlineCompany", reflect.TypeOf((*MockStore)(nil).ListAirlineCompany), arg0)
}

// ListAirports mocks base method.
func (m *MockStore) ListAirports(arg0 context.Context) ([]db.ListAirportsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAirports", arg0)
	ret0, _ := ret[0].([]db.ListAirportsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAirports indicates an expected call of ListAirports.
func (mr *MockStoreMockRecorder) ListAirports(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAirports", reflect.TypeOf((*MockStore)(nil).ListAirports), arg0)
}
